### ISSUE TITLE
Please add LICENSE file to repo

### ISSUE THREAD

**Issue by gmlewis** [fogleman/fauxgl#1]
@fogleman - this looks fantastic.

Can you please add a "LICENSE" file to the top-level directory of the repo?
Ideally, you would choose [Apache-2.0](https://opensource.org/licenses/Apache-2.0), [MIT](https://opensource.org/licenses/MIT), or [BSD](https://opensource.org/licenses/BSD-3-Clause), but choosing one is important to enable others to use your open source repo.

Thank you!

**Comment by adamluzsi** [comment]
+1
