### ISSUE TITLE
Not writing pixel when alpha transparency?

### ISSUE THREAD

**Issue by karimbahgat** [fogleman/fauxgl#10]
I noticed a potential issue. Inside context.go, there's an if/else clause for writing the final pixel value. When there's no alphablending it writes the pixel using `dc.ColorBuffer.SetNRGBA(x, y, color.NRGBA())`. 

However, when there is alpha blending, there's some code to compute the alpha blended color, but it never actually writes the pixel value. If I'm understanding it right, that could be fixed by adding a single line of code. I had to add a line writing the pixel to get it right when I [ported your library to Python](https://github.com/karimbahgat/phauxgl). 

Here is the relevant code block, line 221 of context.go:

				if dc.WriteColor {
					// update color buffer
					if dc.AlphaBlend && color.A < 1 {
						sr, sg, sb, sa := color.NRGBA().RGBA()
						a := (0xffff - sa) * 0x101
						j := dc.ColorBuffer.PixOffset(x, y)
						dr := &dc.ColorBuffer.Pix[j+0]
						dg := &dc.ColorBuffer.Pix[j+1]
						db := &dc.ColorBuffer.Pix[j+2]
						da := &dc.ColorBuffer.Pix[j+3]
						*dr = uint8((uint32(*dr)*a/0xffff + sr) >> 8)
						*dg = uint8((uint32(*dg)*a/0xffff + sg) >> 8)
						*db = uint8((uint32(*db)*a/0xffff + sb) >> 8)
						*da = uint8((uint32(*da)*a/0xffff + sa) >> 8)
					} else {
						dc.ColorBuffer.SetNRGBA(x, y, color.NRGBA())
					}

**Comment by fogleman** [comment]
These lines _are_ writing the pixel value:

```go
*dr = uint8((uint32(*dr)*a/0xffff + sr) >> 8)
*dg = uint8((uint32(*dg)*a/0xffff + sg) >> 8)
*db = uint8((uint32(*db)*a/0xffff + sb) >> 8)
*da = uint8((uint32(*da)*a/0xffff + sa) >> 8)
```

**Comment by karimbahgat** [comment]
Oh, i see now. I thought the .Pix() call only returned the value as a local variable, but i guess it’s an object that is linked to the underlaying data via *. I still have ways to go learning Go, just applied what i knew from Python.
