### ISSUE TITLE
Missing dragon mesh

### ISSUE THREAD

**Issue by md2perpe** [fogleman/fauxgl#4]
The file `dragon.obj` is missing in the repository.

**Comment by fogleman** [comment]
This is intentional because it's a very large file:

https://github.com/fogleman/fauxgl/blob/master/examples/dragon.go#L11-L12

**Comment by md2perpe** [comment]
http://graphics.cs.williams.edu/data/meshes/dragon.zip doesn't work.
How about using https://git-lfs.github.com/ for the file?

**Comment by md2perpe** [comment]
This seems to be basically the same dragon although the one @fogleman has used seems more smooth:
https://www.thingiverse.com/thing:27666
