### ISSUE TITLE
view full object in image programatically?

### ISSUE THREAD

**Issue by jtoy** [fogleman/fauxgl#7]
is there an api call I can use to make it so for every image I load, it uses some heuristic to make most of the object appear in the image? Right now most of my images only show partial views of the STLs. I want to reliably see most of the object in the image.

**Comment by fogleman** [comment]
Use mesh.UnitCube or mesh.BiUnitCube to scale and translate the mesh in a box at the origin.

https://github.com/fogleman/fauxgl/blob/master/mesh.go#L122-L130

**Comment by jtoy** [comment]
Works great, thanks!
